In [2]:
import pandas as pd
human_markers = pd.read_csv("data/human_markers_2021_02_05.tsv", sep = "\t")

In [4]:
human_markers.describe

,speciesType,tissueType,UberonOntologyID,cancerType,cellType,cellName,CellOntologyID,cellMarker,geneSymbol,geneID,proteinName,proteinID,markerResource,PMID,Company
count,2868,2868,2259,2868,2868,2868,2149,2868,2825,2825,2823,2823,2868,2868,248
unique,1,159,151,131,2,467,230,1682,1593,1596,1595,1595,4,1764,8
top,Human,Undefined,UBERON_0005408,Normal,Normal cell,Cancer stem cell,CL_0000034,CD133,PROM1,8842,PROM1,O43490,Experiment,Company,biolegend
freq,2868,560,198,2117,2117,550,237,104,109,109,109,109,2258,248,51

In [5]:
human_markers.head()

,speciesType,tissueType,UberonOntologyID,cancerType,cellType,cellName,CellOntologyID,cellMarker,geneSymbol,geneID,proteinName,proteinID,markerResource,PMID,Company
0,Human,Kidney,UBERON_0002113,Normal,Normal cell,Proximal tubular cell,NaN,Intestinal Alkaline Phosphatase,ALPI,248,PPBI,P09923,Experiment,9263997,NaN
1,Human,Liver,UBERON_0002107,Normal,Normal cell,Ito cell (hepatic stellate cell),CL_0000632,Synaptophysin,SYP,6855,SYPH,P08247,Experiment,10595912,NaN
2,Human,Endometrium,UBERON_0001295,Normal,Normal cell,Trophoblast cell,CL_0000351,CEACAM1,CEACAM1,634,CEAM1,P13688,Experiment,10751340,NaN
3,Human,Germ,UBERON_0000923,Normal,Normal cell,Primordial germ cell,CL_0000670,VASA,DDX4,54514,DDX4,Q9NQI0,Experiment,10920202,NaN
4,Human,Corneal epithelium,UBERON_0001772,Normal,Normal cell,Epithelial cell,CL_0000066,KLF6,KLF6,1316,KLF6,Q99612,Experiment,12407152,NaN

In [9]:

cell_classes = []
for i, row in human_markers.iterrows():
    cell_class = row["cellName"] +  " (" + row["tissueType"] + ")"
    cell_classes.append(cell_class)

In [25]:
a = list(set(cell_classes))

In [29]:
a[0:9]

['Transitional B cell (Blood)',
 'Embryonic stem cell (Embryo)',
 'Macrophage (Undefined)',
 'Bipolar cell (Eye)',
 'Sertoli cell (Seminal plasma)',
 'B cell (Undefined)',
 'Memory B cell (Peripheral blood)',
 'Myeloid-derived suppressor cell (Liver)',
 'Pancreatic progenitor cell (Pancreas)']

In [30]:
len(a)

1127